/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sbic;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import static sbic.Suppliers.tableRowSorter;

public class Suppliers extends javax.swing.JPanel {

    static TableRowSorter tableRowSorter;
    static Supplier selectedSupplier; // contains Item category object from the the currently selected row of table
    static boolean newForm; // is true if form is loaded to  save new and false if form is loaded to update
    static Supplier[] suppliers;

    /**
     * Creates new form Items
     */
    public Suppliers() throws SQLException {
        initComponents();
        loadSuppliers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        supplierForm = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        saveItemCategoryBtn = new javax.swing.JButton();
        nameField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        descriptionField = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tinField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        telephoneField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        addBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        suppliersTable = new javax.swing.JTable();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        refreshBtn = new javax.swing.JButton();

        supplierForm.setSize(new java.awt.Dimension(400, 400));

        jLabel1.setText("Add / Edit Supplier");

        saveItemCategoryBtn.setText("Save");
        saveItemCategoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveItemCategoryBtnActionPerformed(evt);
            }
        });

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        descriptionField.setColumns(20);
        descriptionField.setRows(5);
        jScrollPane2.setViewportView(descriptionField);

        jLabel2.setText("Description");

        jLabel3.setText("Name");

        jLabel5.setText("TIN");

        tinField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Telephone");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(telephoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(58, 58, 58)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(saveItemCategoryBtn)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel3)
                                            .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel5)
                                            .addComponent(tinField))
                                        .addComponent(jLabel6))
                                    .addGap(1, 1, 1))))))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(1, 1, 1)
                .addComponent(tinField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telephoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(saveItemCategoryBtn)
                .addContainerGap())
        );

        javax.swing.GroupLayout supplierFormLayout = new javax.swing.GroupLayout(supplierForm.getContentPane());
        supplierForm.getContentPane().setLayout(supplierFormLayout);
        supplierFormLayout.setHorizontalGroup(
            supplierFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        supplierFormLayout.setVerticalGroup(
            supplierFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        suppliersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(suppliersTable);

        editBtn.setText("Edit");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchFieldKeyReleased(evt);
            }
        });

        jLabel4.setText("Search");

        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refreshBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(editBtn)
                    .addComponent(deleteBtn)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(refreshBtn))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addGap(117, 117, 117))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed

        newForm = true;
        clearSupplierForm();
        supplierForm.setVisible(true);
    }//GEN-LAST:event_addBtnActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void saveItemCategoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveItemCategoryBtnActionPerformed

        try {

            if (newForm) {

                if (nameField.getText().equals("")) {

                    JOptionPane.showMessageDialog(this, "Enter Name", "Add Supplier", JOptionPane.ERROR_MESSAGE);
                } else if (!Validator.isProperName(nameField)) {

                    JOptionPane.showMessageDialog(this, "Name can't be longer than 30 characters.", "Add Supplier", JOptionPane.ERROR_MESSAGE);
                } else {

                    if (Supplier.nameExists(nameField.getText(), "")) {

                        JOptionPane.showMessageDialog(this, "Supplier Name Exists", "Add Supplier", JOptionPane.ERROR_MESSAGE);

                    } else if (Supplier.tinExists(tinField.getText(), "")) {

                        JOptionPane.showMessageDialog(this, "Supplier TIN Exists", "Add Supplier", JOptionPane.ERROR_MESSAGE);
                    } else {

                        Supplier newSupplier = new Supplier(nameField.getText(), descriptionField.getText(), tinField.getText(), telephoneField.getText());
                        if (newSupplier.save()) {
                            JOptionPane.showMessageDialog(this, "Supplier Registered Succesfully", "Add Supplier", JOptionPane.INFORMATION_MESSAGE);
                            supplierForm.setVisible(false);
                            loadSuppliers();
                        }
                    }

                }

            } else {

                if (nameField.getText().equals("")) {

                    JOptionPane.showMessageDialog(this, "Enter Name", "Edit Supplier", JOptionPane.ERROR_MESSAGE);
                } else if (!Validator.isProperName(nameField)) {

                    JOptionPane.showMessageDialog(this, "Name can't be longer than 30 characters.", "Add Supplier", JOptionPane.ERROR_MESSAGE);
                } else {

                    if (Supplier.nameExists(nameField.getText(), selectedSupplier.getName())) {

                        JOptionPane.showMessageDialog(this, "Supplier Name Exists", "Edit Supplier", JOptionPane.ERROR_MESSAGE);

                    } else {

                        selectedSupplier.setName(nameField.getText());
                        selectedSupplier.setDescription(descriptionField.getText());

                        if (selectedSupplier.save()) {
                            JOptionPane.showMessageDialog(this, "Supplier Updated Succesfully", "Edit Supplier", JOptionPane.INFORMATION_MESSAGE);
                            supplierForm.setVisible(false);
                            loadSuppliers();
                        }
                    }

                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(Suppliers.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveItemCategoryBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed

        newForm = false;
        clearSupplierForm();
        nameField.setText(selectedSupplier.getName());
        descriptionField.setText(selectedSupplier.getDescription());
        supplierForm.setVisible(true);

    }//GEN-LAST:event_editBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed

        try {
            if (!selectedSupplier.canDelete()) {

                JOptionPane.showMessageDialog(this, "You can not delete this Supplier because it has items attached to it.", "Delete Supplier", JOptionPane.ERROR_MESSAGE);
            } else {

                if (JOptionPane.showConfirmDialog(this, "Are You Sure You Want To Delete " + selectedSupplier.getName() + "?", "Delete Supplier", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {

                    if (selectedSupplier.delete()) {
                        JOptionPane.showMessageDialog(this, selectedSupplier.getName() + " deleted succesfully!", "Delete Supplier", JOptionPane.INFORMATION_MESSAGE);
                        loadSuppliers();
                    } else {
                        JOptionPane.showMessageDialog(this, "Deleting " + selectedSupplier.getName() + " failed!", "Delete Supplier", JOptionPane.ERROR_MESSAGE);
                    }
                } else {

                }

            }
        } catch (SQLException e) {

        }

    }//GEN-LAST:event_deleteBtnActionPerformed

    private void searchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyReleased
        // TODO add your handling code here:

        String searchKey = searchField.getText();
        if (searchKey.trim().length() == 0) {
            tableRowSorter.setRowFilter(null);
        } else {
            tableRowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + searchKey));
        }
    }//GEN-LAST:event_searchFieldKeyReleased

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        try {
            // TODO add your handling code here:
            loadSuppliers();
        } catch (SQLException ex) {
            Logger.getLogger(Suppliers.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void tinFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tinFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextArea descriptionField;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton saveItemCategoryBtn;
    private javax.swing.JTextField searchField;
    private javax.swing.JFrame supplierForm;
    private javax.swing.JTable suppliersTable;
    private javax.swing.JTextField telephoneField;
    private javax.swing.JTextField tinField;
    // End of variables declaration//GEN-END:variables

    void loadSuppliers() throws SQLException {

        searchField.setText("");

        if (!Session.getLoggedInUser().getRole().equals("Administrator")) {

            addBtn.setEnabled(false);
        }

        editBtn.setEnabled(false);

        deleteBtn.setEnabled(false);

        String tableColumns[] = {"No", "Serial", "Name", "Description", "TIN", "Telephone"};

        suppliers = Supplier.findAll();

        Object tableDataRows[][] = new Object[suppliers.length][6];

        int numberOfRows = 0;

        for (Supplier supplier : suppliers) {

            tableDataRows[numberOfRows][0] = (numberOfRows + 1);
            tableDataRows[numberOfRows][1] = supplier.getId();
            tableDataRows[numberOfRows][2] = supplier.getName();
            tableDataRows[numberOfRows][3] = supplier.getDescription();
            tableDataRows[numberOfRows][3] = supplier.getTIN();
            tableDataRows[numberOfRows][3] = supplier.getTelephone();

            numberOfRows++;
        }

        TableModel itemCategoriesTableModel = new DefaultTableModel(tableDataRows, tableColumns) {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        suppliersTable.setModel(itemCategoriesTableModel);

        ListSelectionModel itemCategoriesTableSelectionModel = suppliersTable.getSelectionModel();

        tableRowSorter = new TableRowSorter(suppliersTable.getModel());

        suppliersTable.setRowSorter(tableRowSorter);

        itemCategoriesTableSelectionModel.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {

                if (itemCategoriesTableSelectionModel.getMaxSelectionIndex() == -1) {

                    editBtn.setEnabled(false);

                    deleteBtn.setEnabled(false);

                } else {

                    if (Session.getLoggedInUser().getRole().equals("Administrator")) {
                        editBtn.setEnabled(true);
                        
                        deleteBtn.setEnabled(true);
                        
                    }
                    selectedSupplier = Supplier.find((int) suppliersTable.getValueAt(suppliersTable.getSelectedRow(), 1));
                }
            }
        });
    }

    void clearSupplierForm() {

        nameField.setText("");
        descriptionField.setText("");
        tinField.setText("");
        telephoneField.setText("");

    }

}
